import React from 'react';
import Head from "next/head";
import Header from './Header';
import Info from './Info';

export default function Layout({ children }) {
  return (
    <>
        <Head>
            <title>EazyShop</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        
        <main>
            <Header></Header>
            <div className="children">
              { children }
            </div>
        </main>
    </>
  )
}
