import laptop1 from "../images/product-126.jpg"
import laptop2 from "../images/product-131.jpg"
import laptop3 from "../images/product-26.jpg"
import laptop4 from "../images/product-14.png"
import phone1 from "../images/product-127.jpg"
import phone2 from "../images/product-130.jpg"
import phone3 from "../images/product-125.jpg"
import phone4 from "../images/product-7.jpg"
import gadget1 from "../images/product-22.jpg"
import gadget2 from "../images/product-50.jpg"
import gadget3 from "../images/product-40.jpg"
import gadget4 from "../images/product-25.jpg"
import watch1 from "../images/product-120.jpg"
import watch2 from "../images/product-122.jpg"
import watch3 from "../images/product-123.jpg"
import watch4 from "../images/product-128.jpg"


export const products = {
    laptops:[{
        id: 1,
        image: laptop1,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
        count: 0,
    },{ id:2,
        image: laptop2,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
        count: 0,
    },{ id: 3,
        image: laptop3,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
        count: 0,
    },{ id: 4,
        image: laptop4,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
        count: 0,
    },{ id: 5,
        image: laptop2,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
        count: 0,
    } ],

    phones: [{
        id:10,
        image: phone1,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
        count: 0,
    },{ id:20,
        image: phone2,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
        count: 0,
    },{ id:30,
        image: phone3,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
        count: 0,
    },{ id:40,
        image: phone4,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
        count: 0,
    },{ id:50,
        image: phone2,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
        count: 0,
    } ],

    gadgets: [{
        id:100,
        image: gadget1,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
        count: 0,
    },{ id: 200,
        image: gadget2,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
        count: 0,
    },{ id: 300,
        image: gadget3,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
        count: 0,
    },{ id: 400,
        image: gadget4,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
        count: 0,
    },{ id: 500,
        image: gadget2,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
    } ],

    watches:[{
        id:1000,
        image: watch1,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: "500",
        count: 0,
    },{ id: 2000,
        image: watch2,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
        count: 0,
    },{ id:3000,
        image: watch3,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
        count: 0,
    },{
        id:4000,
        image: watch4,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
        count: 0,
    }, {
        id:5000,
        image: watch2,
        name: "samsung galaxy international vs",
        rating: 4,
        amount: 500,
        count: 0,
    }],
}